[project]
name = "fastapi-sqlmap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "asyncpg>=0.31.0",
    "celery>=5.6.1",
    "celery-types>=0.24.0",
    "eventlet>=0.40.4",
    "fastapi>=0.127.0",
    "gevent>=25.9.1",
    "pre-commit>=4.5.1",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.21",
    "redis>=7.1.0",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]

[tool.black]
line-length = 88
target-version = ["py312"]

exclude = '''
(
    \.venv
  | venv
  | alembic/versions
  | alembic
  | migrations
  | build
  | dist
)
'''
