"""modify SqlmapScanPayload

Revision ID: 3b0e4bf87a83
Revises: 8b8aab38f973
Create Date: 2026-01-09 17:38:18.020418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b0e4bf87a83"
down_revision: Union[str, Sequence[str], None] = "8b8aab38f973"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
