"""init sqlmap tables

Revision ID: 648b6521fe6d
Revises: 
Create Date: 2025-12-24 16:05:20.496698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '648b6521fe6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlmap_scan_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('dbms', sa.String(length=64), nullable=True),
    sa.Column('vulnerable', sa.Boolean(), nullable=False),
    sa.Column('injection_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dump_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlmap_scan_results')
    # ### end Alembic commands ###
