"""update sqlmap_task tables

Revision ID: 682d067b7b79
Revises: af0f871d00dc
Create Date: 2025-12-30 17:10:59.425847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682d067b7b79'
down_revision: Union[str, Sequence[str], None] = 'af0f871d00dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sqlmap_task_results', sa.Column('scan_url', sa.String(length=2048), nullable=False))
    op.add_column('sqlmap_task_results', sa.Column('scan_level', sa.Integer(), nullable=False))
    op.add_column('sqlmap_task_results', sa.Column('scan_risk', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sqlmap_task_results', 'scan_risk')
    op.drop_column('sqlmap_task_results', 'scan_level')
    op.drop_column('sqlmap_task_results', 'scan_url')
    # ### end Alembic commands ###
