"""modify SqlmapScanPayload

Revision ID: 6ba4224e4425
Revises: 80f489f09feb
Create Date: 2026-01-09 17:36:10.133105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ba4224e4425"
down_revision: Union[str, Sequence[str], None] = "80f489f09feb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sqlmap_task_results",
        sa.Column("celery_task_id", sa.String(length=64), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sqlmap_task_results", "celery_task_id")
    # ### end Alembic commands ###
