"""modify  sqlmapscanlog clery_task_id

Revision ID: 80f489f09feb
Revises: d635ec769dd4
Create Date: 2026-01-09 17:32:58.960949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80f489f09feb"
down_revision: Union[str, Sequence[str], None] = "d635ec769dd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sqlmap_scan_logs",
        "celery_task_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sqlmap_scan_logs",
        "celery_task_id",
        existing_type=sa.String(length=64),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
