"""init sqlmap_scan_logs  tables

Revision ID: 8420a4c060b6
Revises: be1465ba5c07
Create Date: 2026-01-05 11:48:49.757391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8420a4c060b6'
down_revision: Union[str, Sequence[str], None] = 'be1465ba5c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlmap_scan_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_time', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sqlmap_scan_logs_created_at'), 'sqlmap_scan_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sqlmap_scan_logs_task_id'), 'sqlmap_scan_logs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sqlmap_scan_logs_task_id'), table_name='sqlmap_scan_logs')
    op.drop_index(op.f('ix_sqlmap_scan_logs_created_at'), table_name='sqlmap_scan_logs')
    op.drop_table('sqlmap_scan_logs')
    # ### end Alembic commands ###
