"""update sqlmap_task tables

Revision ID: be1465ba5c07
Revises: 682d067b7b79
Create Date: 2025-12-30 17:19:07.227118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1465ba5c07'
down_revision: Union[str, Sequence[str], None] = '682d067b7b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sqlmap_task_results', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sqlmap_task_results', 'created_at')
    # ### end Alembic commands ###
