"""add sqlmapscanlog clery_task_id

Revision ID: d635ec769dd4
Revises: 474bd6829204
Create Date: 2026-01-09 17:31:58.379259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d635ec769dd4"
down_revision: Union[str, Sequence[str], None] = "474bd6829204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sqlmap_scan_logs", sa.Column("celery_task_id", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sqlmap_scan_logs", "celery_task_id")
    # ### end Alembic commands ###
